### ISSUE TITLE
WooCommerce - Info notices layout incorrectly due to CSS grid

### ISSUE THREAD

**Issue by dswebsme** [pressden/emma#126]
This one is going to be fully documented here in case reproducing it proves difficult. The steps to reproduce (as far as I can tell) are to add a few items to a cart and then modify / resave those products causing the cart items to become invalidated / outdated.

The resulting notices, which appear to be text only are styled as pictured below.
<img width="1251" alt="outdated-cart-notices" src="https://user-images.githubusercontent.com/9062957/102953230-d391c780-449e-11eb-970e-7a0da17adc4d.png">

The code looks like this:
```
<div class="woocommerce-info">
	Amazonite Small Sphere has been removed from your cart
	because it has since been modified. You can add it back to your cart
	<a href="https://www.mustloveminerals.com/product/amazonite/">here</a>.
</div>
```

Upon investigation, it appears that CSS grid is the culprit. Specifically, the text and anchor are being split up and rearranged using `grid-row: 1` and split apart in unexpected ways via `grid-row-gap` and `grid-column-gap`.

The anchor specifically cited above is affected by selectors like these:
```
.woocommerce-page .woocommerce-message *,
.woocommerce-page .woocommerce-message .button,
.woocommerce-page .woocommerce-info *,
.woocommerce-page .woocommerce-info .button
```

**Comment by eric-michel** [comment]
Easy replication steps:

- Add simple product to cart and visit cart
- Change product to be variable (no actual variations need to be added)
- Refresh cart
- Message in question should appear
