### ISSUE TITLE
Find Dashicons Alternative

### ISSUE THREAD

**Issue by eric-michel** [pressden/emma#148]
More than half of our total CSS weight now is `dashicons`. Finding maybe an SVG alternative that loads only the icon actually used rather than a font file would probably be preferable.

**Comment by dswebsme** [comment]
https://make.wordpress.org/design/2020/04/20/next-steps-for-dashicons/

It seems everyone is in agreement that an SVG based alternative that allows sites to load icons selectively based on use is the ideal path forward. The article linked above is from nearly a year ago and no further development is actively being done on the Dashicons font.

I'll do a bit more digging to see how they've faired with adding SVG support within that timeframe. The 5.5 release was the last update to Dashicons and we've just hit 5.7 recently so I'm sure they've chosen a direction by now.

**Comment by eric-michel** [comment]
It might be that this problem will resolve itself. See this comment from that thread:
![image](https://user-images.githubusercontent.com/45110062/112052864-02651b80-8b2a-11eb-906e-416ab46b9dfe.png)

If they make the icon component usable via CSS, we could seamlessly transition that way. Something to look for going forward.

**Comment by eric-michel** [comment]
This has been resolved in #182
