### ISSUE TITLE
Gutenberg - List Block - Fix spacing of nested lists

### ISSUE THREAD

**Issue by dswebsme** [pressden/emma#188]
The list block supports nested lists but our CSS only applies spacing to top-level list items. That same spacing cascades down into nested sub-lists leaving all sub-level list items very spread out, not grouped as one would expect to see.

**Comment by eric-michel** [comment]
@dswebsme based on what I'm seeing, this has been resolved (possibly accidentally). Can you confirm?

This is how it looks for me on an updated test site:
![image](https://user-images.githubusercontent.com/45110062/142928552-70f29294-4dfc-49b2-be45-f201fbc32758.png)

**Comment by dswebsme** [comment]
Looks good. May have been a false alarm coming from some child theme styles. Thanks for checking @eric-michel. Closing this one out.
