### ISSUE TITLE
Get webpack to output a separate admin-side CSS file that uses core variables

### ISSUE THREAD

**Issue by eric-michel** [pressden/emma#45]
It's getting to where we really need to get this done. The admin side is starting to look less and less like the frontend.

**Comment by dswebsme** [comment]
This is complete but it comes with some broad sweeping changes here as well as in emma-starter.

@eric-michel See below for updated entrypoints.

The base webpack configuration has been updated to support code splitting. To bring sanity to the naming conventions, they've all been updated.

Previously it looked like this:
Entry > `js/index.js`
SASS > `sass/style.scss`
compiled > `dist/app.js` & `dist/app.css`

Now things are quite a bit more consistent. Code splitting introduces two entry points:

THEME (for the customer facing site)
-------------------
Entry > `theme.js`
SASS > `sass/emma-theme.scss`
compiled `dist/theme.js` & `dist/theme.css`

ADMIN (for the WP backend and editor)
-------------------
Entry > `admin.js`
SASS > `sass/emma-admin.scss`
compiled `dist/admin.js` & `dist/admin.css`

Be mindful that updating to the latest version of Emma with these updates in place will likely result in missing CSS / JS files. The child theme must be updated manually (get the latest webpack base config file and rename / move files to match the updated structure.
