### ISSUE TITLE
Cover block inconsistencies

### ISSUE THREAD

**Issue by dswebsme** [pressden/emma#57]
In trying out some different uses of the cover block I'm getting inconsistent behaviors. Below are some examples but many variations should be tested.

1. When a cover block has siblings the height: 100%; style causes content below it to get pushed out of view. Example: `Columns > Column` contains cover, heading, paragraph. This looks good in the editor (the preferred behavior) but when saved and viewed on the frontend the heading and paragraph are pushed down below the column container. **NOTE:** Placing the cover inside a group block (so it's the only child) resolves this issue on the front-end.

2. Using a responsive grid block where items within the grid contain only cover blocks, the covers appear very narrow. I believe this is due to grid items not having any width of their own but rather are flexible to match the width of their children (this is a guess based on what I was seeing).

**Comment by eric-michel** [comment]
@dswebsme Regarding these item:

1. I'm seeing the same thing - the funny thing is that this it he default CSS from Gutenberg. I have no idea why they'd want to set height to 100% on that block. I'm going to set it to auto and do some testing to make sure it doesn't break anything.
2. See if your horizontal Alignment is set to Stretch:
![image](https://user-images.githubusercontent.com/45110062/80999955-81b70700-8e13-11ea-89c7-c8fe76f495eb.png)

That's the default for me, but yours might be set differently for some reason. When it's set to stretch it looks correct, but when set to Center it does indeed become very narrow. I'm looking into that separately, but I think most of the time what you'll want when using cover blocks is stretch anyway.

**Comment by eric-michel** [comment]
Ok, yes the `Center` horizontal alignment is going to cause problems with how the cover block works. I'm not sure there's a simple way to fix that, but I'm also sure we really need to worry too much about fixing it given that you'll pretty much always want to use `Stretch` in those circumstances.

**Comment by dswebsme** [comment]
Thanks for the information. I'll take a look at my default settings to see if my defaults differ from yours. If it does that may be a bug we can address as well.

**Comment by dswebsme** [comment]
Regarding the `height: 100%` style for cover blocks, my initial thought was that the cover block is meant to `fill` its' parent container (since wrapping `cover` in a `group` block fixes the issue). That's just a guess though. It just seems odd considering that it displays correctly without a `group` wrapper on the backend. Thanks for looking into options.
